# If true, players must have permission (specified by permission-node) to use the lightlevel command
check-permission: true

# The permission node required to use the lightlevel command
permission-node: "lightdisplay"

# If true, display messages in the action bar. If false, display messages in the chat
display-in-actionbar: true

# The code of the language to use for messages (e.g., 'en' for English, 'cs' for Czech)
language-code: 'en'
